-- Verity Bills Rebuild — Phase 1: Data Layer
-- Adds enrichment columns to bills table and creates the generate-bill-summary support.
--
-- Run: supabase db execute --project-ref zmmglikiryuftqmoprqm < scripts/migration_bills_rebuild.sql

-- ── New columns on bills ────────────────────────────────────────────────────

-- Expanded AI summary (2-3 sentences, generated by Edge Function)
ALTER TABLE bills ADD COLUMN IF NOT EXISTS expanded_summary text;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS summary_generated_at timestamptz;

-- Sponsor tracking (FK to members, nullable — many older bills have no sponsor data)
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sponsor_id uuid REFERENCES members(id);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sponsor_party text;

-- Narrative enrichment (derived, updated by cron or on-demand)
ALTER TABLE bills ADD COLUMN IF NOT EXISTS narrative_status text DEFAULT 'unknown';
  -- Values: moving_quickly, progressing, stalled, died_silently, became_law, defeated, unknown
ALTER TABLE bills ADD COLUMN IF NOT EXISTS is_live boolean DEFAULT false;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS days_since_movement integer;

-- Political analysis cache (generated by Edge Function, cached as JSONB)
ALTER TABLE bills ADD COLUMN IF NOT EXISTS politics_cache jsonb;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS politics_generated_at timestamptz;

-- Personal impact cache table (per-user, per-bill)
CREATE TABLE IF NOT EXISTS bill_personal_impact (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_id uuid NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  profile_hash text NOT NULL, -- hash of relevant user profile fields, for cache invalidation
  affects_you text NOT NULL DEFAULT 'unknown', -- 'yes', 'maybe', 'no', 'unknown'
  affects_you_reason text,
  how_it_affects_you text,
  who_benefits text,
  who_pays text,
  quantified_impact jsonb, -- Pro tier only; null if not quantifiable
  generated_at timestamptz DEFAULT now(),
  UNIQUE(bill_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_bill_impact_user ON bill_personal_impact(user_id, bill_id);
CREATE INDEX IF NOT EXISTS idx_bill_impact_bill ON bill_personal_impact(bill_id);

-- RLS
ALTER TABLE bill_personal_impact ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "Users read own impact" ON bill_personal_impact
    FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY "Service role full access impact" ON bill_personal_impact
    FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Indexes for the new columns ─────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_bills_is_live ON bills(is_live) WHERE is_live = true;
CREATE INDEX IF NOT EXISTS idx_bills_narrative ON bills(narrative_status);
CREATE INDEX IF NOT EXISTS idx_bills_sponsor ON bills(sponsor_id) WHERE sponsor_id IS NOT NULL;

-- ── Enrichment function: compute narrative_status and is_live ────────────────
-- Called by a cron job or after bill ingestion updates

CREATE OR REPLACE FUNCTION enrich_bill_narrative()
RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT id, current_status, last_updated, date_introduced FROM bills LOOP
    DECLARE
      s text := lower(coalesce(r.current_status, ''));
      days_since int := EXTRACT(DAY FROM (now() - coalesce(r.last_updated, r.date_introduced, now())))::int;
      live boolean := false;
      narrative text := 'unknown';
    BEGIN
      -- Determine is_live
      IF s LIKE '%passed%' OR s LIKE '%assent%' OR s LIKE '%act %' OR s = 'act'
         OR s LIKE '%defeated%' OR s LIKE '%withdrawn%' OR s LIKE '%lapsed%'
         OR s = 'in search index' OR s = 'historical' THEN
        live := false;
      ELSE
        live := true;
      END IF;

      -- Determine narrative_status
      IF s LIKE '%assent%' OR (s LIKE '%passed%' AND s NOT LIKE '%not passed%') THEN
        narrative := 'became_law';
      ELSIF s LIKE '%defeated%' OR s LIKE '%not passed%' THEN
        narrative := 'defeated';
      ELSIF s LIKE '%withdrawn%' OR s LIKE '%lapsed%' THEN
        narrative := 'died_silently';
      ELSIF s = 'in search index' OR s = 'historical' THEN
        narrative := 'died_silently';
      ELSIF live AND days_since <= 14 THEN
        narrative := 'moving_quickly';
      ELSIF live AND days_since <= 60 THEN
        narrative := 'progressing';
      ELSIF live AND days_since > 60 THEN
        narrative := 'stalled';
      END IF;

      UPDATE bills SET
        is_live = live,
        narrative_status = narrative,
        days_since_movement = days_since
      WHERE id = r.id
        AND (bills.is_live IS DISTINCT FROM live
          OR bills.narrative_status IS DISTINCT FROM narrative
          OR bills.days_since_movement IS DISTINCT FROM days_since);
    END;
  END LOOP;
END;
$$;

-- Run it once now to populate existing bills
SELECT enrich_bill_narrative();
